### ISSUE TITLE
Imdb\Image not PSR4 compliant

### ISSUE THREAD

**Issue by jcvignoli** [duck7000/imdbGraphQLPHP#114]
In order to be fully PSR4 compliant and be found when using composer, Imdb\Image class must be named as a file as Image.php (instead of ImageFunctions.php)

**Comment by duck7000** [comment]
Mm i'll admit i don't no jack shit about PSR4 standards but i'll take your word for it.

So the filename cannot be camelCase and must be a single name i understand?

Of course i will change that

**Comment by duck7000** [comment]
Okay after a little reading it has nothing to do with camelCase or not, it just needs to be a specific order

**Comment by jcvignoli** [comment]
I guess you should keep your coding formatting, it's working so far. I'm trying to integrate your library, it's gonna take time but expect more reports ;)

**Comment by duck7000** [comment]
This is fixed in latest commit

I'l try but you have to understand that i'm doing this as a hobby project.
And that i'm not a professional as i have no education in programming what so ever, it is all self thought.
I used to be a car mechanic but due to medical issues i can't do that anymore so i "learned" programming.
I must admit that i learned a lot by looking at how imdbphp is build and i now understand more and more why Tboothman made certain choices that i didn't understand at first.

so i'm actually glad that you point this issues out as i would never think of that, so yes keep them coming haha

With this kind of help this library will getting better, that is the main goal!

**Comment by duck7000** [comment]
And for your information i changed a lot of methods lately so be prepared for changes.
I documented the most important ones in issues labeled important but there are more changes, thumbnail sizes etc.
if you encounter changes, read the wiki pages as they are adjusted as well

**Comment by jcvignoli** [comment]
No worries @duck7000, I'm not in a hurry, I'm also working on my library on spare time, and... I've no education in programming either ;) But since I'm starting using you're library, I'll get back to you with the little I know.

Thanks for your work, happy you found a hobby that's of interest to you despite your medical condition. I hope you'll get better.

**Comment by duck7000** [comment]
Thanks but my condition is permanent and i'm at a disability welfare unfortunately. this is almost 30 years now so i am used to it.
But that gives me time to do this kind of things to look on the bright side of life.

**Comment by jcvignoli** [comment]
I guess we cannot change the cards we are dealt, just how we play the hand. Continue finding the bright side of life ;)
