### ISSUE TITLE
Added composer

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbGraphQLPHP#77]
@georgeFive
@mosource21
@All

I reacted on a user from imdbphp about the project been dead and pointed at my repo and he/she pointed me to use packagist. At first i refused and did get a thumbs down as result, no further communication at this point with that user despite i did communicate further about this.
Well i didn't know it existence let i know how that works, but i looked in to this and managed to get this to packagist.

So from now on imdbGraphQLPHP is on packagist under duck7000/imdb-graphql-php (they don't accept uppercase..)
dev-master is available and tag releases (only the last tag release for now as all the other releases don't have composer.json file)
It is auto updated if there was a push update from me.

I noticed that imdbphp has more kinds of package or distribution channels so i wonder if this project should also be on those channels?
Personally i don't use any package manager (except from EndeavourOS, Arch linux) as this, or my other projects, are not that hard to use.

So what is your opinion about this?
And should i add my other project (musicbrainzPHP for example)?

**Comment by GeorgeFive** [comment]
I think any exposure is good exposure, so I'm definitely not going to say don't do it.... but like you, I don't use any package managers, and never have.  I'm just paranoid about developers adding / changing something in their code which breaks my personal use cases, so I like having the luxury of updating when I have the time to play with any potential bugs that may show up with an update.

**Comment by duck7000** [comment]
Yes from a exposure stand point i added this to packagist, not because i'm a fan of a package manager (i'm not!)
I, like you, would be in control, not depending on other services without knowing for sure what is happening.

So i will add musicBrainzPHP as well for the same reason.

Maybe it will get more attention to the project so more people can use it. As far as i know there is no other project to get imdb info with GraphQL that is so complete as ours. And that is not only my work as i need users to test stuff.
So a big thanks to the users as well.
Thanks for your comment!

**Comment by mosource21** [comment]
Unfortunately old school here also no package managers for me.  

Exposure can be good and bad.  

If you think you can handle the potential increase in issues (PRs, questions, good and bad etc) the increased exposure will get more eyes on the project and should be a positive.  

If you are wary of the potential extra time you may need to invest into your projects that more exposure may bring do it gradually.

Remember you are not being paid and generally people are more likely the complain rather than compliment so do not be put off by negative feedback (like the thumbs down) just ignore it and think of all the positive feedback received instead.

**Comment by duck7000** [comment]
@mosource21 

I am aware of what you are saying, but those are the only projects i work on so time wise i can handle it.
We will see how that goes, if it grows over my head i pull it back from packagist.

Thanks for your comment!
