### ISSUE TITLE
Added NameSearchAdvanced class

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbGraphQLPHP#93]
Works the same as TitleSearchAdvanced but for Names. https://www.imdb.com/search/name/
Adult names are included, if anyone want this as a parameter or config setting let me know.

In this version i overhauled the whole constraints part, it now only includes the constraints that are necessary (because a parameter has a valid value)
For Users this has no changes, only code changes.
So the query is shorter, if all parameters are used it will not (but that will never happen as the search doesn't make any sense in that case)
It is also much easier to add constraints.
If this (after your testing) works i will add this also to TitleSearchAdvanced class

I also added thumbnail images to the output array, settings are in config.

And i added totalFoundResults to the output array. This needs some explanation:
This is the total number of Names found by the query, this will not be the total returned results! Returned results are limited by config option nameSearchAdvancedAmount
You can see what i mean at the top of this page https://www.imdb.com/search/name/?birth_monthday=11-24 
Next to Expand All you will see total query results (1464) but the list with names is limited to 50

example uses:
borntoday https://www.imdb.com/search/name/?birth_monthday=11-24
Or search within Names for specific birthdates or deathdates etc

All info is in the wiki page

Check it out if you like and let me know how it works
Report any issues/bugs here please

**Comment by duck7000** [comment]
@GeorgeFive

I know you won't be using this new NameSearchAdvanced class but i have a question that you might can answer

In this NameSearchAdvanced i added all info that imdb is displaying as the result of the search.

Do you think that is too much? as this is not in TitleSearchAdvanced?
Or do you think TitleSearchAdvanced does need this extra info as well? (at the time we choose to include only the necessary ones to keep the query down but that might no longer an issue?)

**Comment by GeorgeFive** [comment]
Not sure I'll be of much help with this one... in my personal use case for TSA, I really only need id, title, year, and type (movie/TV/etc).  Anything else I may need, I could query with the normal title lookup (I don't need anything else, though).

With that said, I could definitely see a use case for including extra info.... some people would probably want coverurl, some may want the country, others want the language, etc.

I think a nice middle ground might be the best way to go.... think of what you would see in a search results page and go from there.  If you need the extra info, you would click the result (use normal title lookup)... otherwise, you get the core info at a glance.

I don't think I need the total results, but I'm sure it's nice for internal pagination.

**Comment by duck7000** [comment]
the middle ground is what i did with NameSearchAdvanced, every value is included that imdb uses in the search results.
So i will leave that like it is.
I might however remove the total results, the output array will then be the same as TSA
Or is it better to make TSA the same as NSA?

As for TSA i can include the same values to it but the query part will be getting longer , good idea or not?

I struggle a bit with this kind of questions/issues
